server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/
  instance:
    metadata-map:
      cluster: xbang
spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://47.104.171.254:3306/security-demo?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Soar18786611964
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath*:/mysql.sql
    continue-on-error: false
    initialization-mode: never

#配置zipkin 的端口号及协议(默认8080 http)
armeria:
    ports[0]:
      port: 8080
      protocols:
          - http

zipkin:
  storage:
    type: mysql


