server:
  port: 9099

spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/longbangying/config-center.git
          search-paths: eureka-server,provider-demo
          #search-paths: /**   # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开
eureka:
  client:
    enabled: false
