

spring:
  application:
    name: provider-demo
server:
  port: 9091


eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:80/eureka/

#,http://eureka2.com:8082/eureka/,http://eureka3.com:8083/eureka/