

spring:
  application:
    name: provider-demo
  profiles:
    active: #2
  zipkin:
    base-url: http://localhost:8080
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/
  instance:
    metadata-map:
      cluster: xbang
    prefer-ip-address: true
    ip-address: 192.168.153.1


local:
  file:
    store-path: d:/file-center/
logging:
  level:
    org:
      springframework:
        cloud:
          commons:
            util: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"
