

spring:
  application:
    name: provider-demo
  profiles:
    active: 1
server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/


local:
  file:
    store-path: d:/file-center/
