server:
  port: 9090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #{application}是占位符 代表应用名，当客户端向Config Server发起获取配置的请求时，Config Server会根据客户端的Spring.application.name信息来填充{application}占位符以定位配置资源的存储位置，实现根据微服务应用属性动态获取不同位置的配置
          uri: https://github.com/longbangying/cloud-config-center.git
          #search-paths: eureka-server,provider-demo,config-client-demo
          search-paths: /**   # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开paths
          repos:
            dev:
              uri: https://github.com/longbangying/config-center.git
              pattern: dev/{application}/*
            prd:
              uri: https://github.com/longbangying/config-center.git
              pattern: prd/{application}/*
            xbang:
              uri: https://github.com/longbangying/config-center.git
              pattern: config-client-demo/demo*
    #打开 /actuator/bus-refresh 端点   打开这个端点之后，当有多个服务的时候，就不用挨个的调用 /actuator/refresh 进行刷新
    #只需要调一次 /actuator/bus-refresh 端点就行了(config-server或者config-client 中的一个就可)
    bus:
      refresh:
        enabled: true
  kafka:
    #指定kafka 地址
    bootstrap-servers: 47.104.171.254:9092
    consumer:
      #
      group-id: spring-cloud-bus

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server: trace
#端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka