server:
  port: 9099

spring:
  application:
    name: consumer1
  zipkin:
    base-url: http://localhost:8080
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/
  instance:
    #metadata-map:
    #  cluster: xbang
    prefer-ip-address: true
    ip-address: 192.168.153.1

logging:
  level:
    com:
      example:
        consumer1:
          service:
            face: debug

# feign 超时配置  和 hystrix 搭配才生效
feign:
  client:
    config:
      default:
        logger-level: full
        connectTimeout: 10000
        readTimeout: 100000

  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
    endpoints:
      web:
        exposure:
          include: '*'