server:
  port: 9099

spring:
  application:
    name: consumer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


logging:
  level:
    com:
      example:
        consumer1:
          service:
            face: debug
feign:
  client:
    config:
      default:
        logger-level: full
  hystrix:
    enabled: true