eureka:
  instance:
    hostname: eureka1.com
  client:
    service-url:
      defaultZone: http://eureka2.com:8082/eureka/,http://eureka3.com:8083/eureka/
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8081