server:
  port: 80

spring:
  application:
    name: eurekaserver
  #cloud:
   # config:
     # uri: http://localhost:9099

eureka:
  instance:
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false


