eureka:
  instance:
    hostname: eureka3.com
  client:
    service-url:
      defaultZone: http://eureka1.com:8081/eureka/,http://eureka2.com:8082/eureka/
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8083